import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col bg-white dark:bg-slate-950">
      <header className="border-b bg-white dark:bg-slate-900 sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-4 py-4">
          <div className="flex items-center justify-center relative">
            <Link href="/">
              <Button variant="ghost" size="sm" className="absolute left-0" data-testid="button-back">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back
              </Button>
            </Link>
            <img 
              src="/logo.png" 
              alt="TeacherBuddy" 
              className="h-16 object-contain"
              data-testid="img-logo"
            />
          </div>
        </div>
      </header>

      <main className="flex-1 py-12 px-4">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-slate-100 mb-4">
              Terms of Use and Privacy Policy
            </h1>
            <p className="text-slate-500 dark:text-slate-400">Last Updated: January 14, 2026</p>
            <div className="w-20 h-1 bg-orange-500 mx-auto rounded-full mt-4" />
          </div>

          <div className="prose prose-slate dark:prose-invert max-w-none">
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-8">
              This document constitutes a legally binding agreement ("Agreement") between you ("User," "you," or "your") and the operator of the TeacherBuddy application ("TeacherBuddy," "we," "us," or "our"). By accessing or using the TeacherBuddy platform—including its web and mobile applications—you expressly consent to the terms set forth herein.
            </p>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">1. Acceptance of Terms</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                The TeacherBuddy platform is intended exclusively for use by individuals who are at least eighteen (18) years of age and acting in a professional capacity as educators, administrators, or affiliated school personnel. Your use of the platform signifies your acceptance of this Agreement and compliance with all applicable laws and regulations.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">2. Description of Services</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                TeacherBuddy provides digital tools designed to assist educators in tasks including, but not limited to: lesson planning, drafting professional correspondence, and sourcing educational materials. All content generated by the platform is provided for informational and preparatory purposes only. Users bear sole responsibility for verifying the accuracy, appropriateness, and compliance of any output with institutional, curricular, and legal standards.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">3. Collection and Use of Personal Data</h2>
              
              <h3 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-3 mt-6">3.1 Data Collected</h3>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">We collect the following categories of personal data:</p>
              <ul className="list-disc pl-6 text-slate-700 dark:text-slate-300 space-y-2 mb-4">
                <li>(a) Account information: name and professional email address;</li>
                <li>(b) Technical data: IP address, device identifiers, operating system, browser type, and usage logs;</li>
                <li>(c) User inputs: text prompts, saved drafts, and preferences submitted through the interface.</li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-3 mt-6">3.2 Data Not Collected</h3>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">TeacherBuddy does not collect, process, store, or transmit:</p>
              <ul className="list-disc pl-6 text-slate-700 dark:text-slate-300 space-y-2 mb-4">
                <li>Personally identifiable information (PII) relating to students or minors;</li>
                <li>Academic records, behavioral assessments, or institutional databases;</li>
                <li>Biometric, health, or sensitive demographic data.</li>
              </ul>

              <h3 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-3 mt-6">3.3 Purpose of Processing</h3>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">Personal data is processed solely for the purposes of:</p>
              <ul className="list-disc pl-6 text-slate-700 dark:text-slate-300 space-y-2">
                <li>(i) Providing and maintaining the functionality of the platform;</li>
                <li>(ii) Personalizing user experience;</li>
                <li>(iii) Ensuring system security and integrity;</li>
                <li>(iv) Complying with legal obligations.</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">4. Data Security Measures</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
                We implement industry-standard technical and organizational measures to protect personal data, including:
              </p>
              <ul className="list-disc pl-6 text-slate-700 dark:text-slate-300 space-y-2 mb-4">
                <li>Encryption of data in transit via TLS 1.2 or higher;</li>
                <li>Encryption of stored data at rest using AES-256;</li>
                <li>Hosting on infrastructure certified under ISO/IEC 27001;</li>
                <li>Regular vulnerability assessments and access controls.</li>
              </ul>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                Notwithstanding these measures, no electronic transmission or storage system is 100% secure. Users acknowledge this inherent risk.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">5. Third-Party Disclosures and AI Training</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                We do not sell, lease, rent, or otherwise disclose personal data to third parties for advertising, marketing, or commercial purposes. User inputs are not used to train third-party artificial intelligence models. Aggregated and anonymized data may be used for internal product improvement, provided such data cannot reasonably be used to re-identify any individual. Where required by applicable law (e.g., GDPR Article 22), explicit prior consent will be obtained for any processing involving automated decision-making.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">6. Region-Specific Legal Compliance</h2>
              
              <h3 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-3 mt-6">6.1 European Economic Area (GDPR)</h3>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
                Processing is based on Article 6(1)(b) (performance of a contract) and Article 6(1)(f) (legitimate interests). Data subjects retain rights of access, rectification, erasure, restriction, portability, and objection. Requests shall be submitted to the contact specified in Section 11.
              </p>

              <h3 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-3 mt-6">6.2 India (Digital Personal Data Protection Act, 2023)</h3>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
                TeacherBuddy acts as a Data Fiduciary under the DPDPA. Consent is obtained at the point of account creation. Cross-border transfers of personal data comply with Chapter V of the DPDPA and occur only to jurisdictions ensuring adequate data protection standards.
              </p>

              <h3 className="text-lg font-medium text-slate-800 dark:text-slate-200 mb-3 mt-6">6.3 United States</h3>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                The platform complies with the California Online Privacy Protection Act (CalOPPA) and the Children's Online Privacy Protection Act (COPPA). The service is not directed toward individuals under the age of thirteen (13), and we do not knowingly collect personal information from children.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">7. Minors and Parental Consent</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                TeacherBuddy is not intended for use by individuals under the age of eighteen (18). The platform does not solicit, collect, or process personal data from minors, directly or indirectly. In the event that a minor accesses the platform through a shared device, no persistent identifiers or account data are created, and session data is automatically purged within twenty-four (24) hours. No parental consent mechanism is implemented, as the service falls outside the scope of COPPA and analogous regulations.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">8. User Obligations</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">You agree to:</p>
              <ul className="list-disc pl-6 text-slate-700 dark:text-slate-300 space-y-2">
                <li>(a) Use the platform in accordance with all applicable laws and professional ethics;</li>
                <li>(b) Refrain from unauthorized access, reverse engineering, or automated scraping;</li>
                <li>(c) Maintain the confidentiality of authentication credentials;</li>
                <li>(d) Assume full liability for the use, adaptation, and dissemination of any content generated through the platform.</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">9. Disclaimers and Limitation of Liability</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed uppercase text-sm">
                THE PLATFORM IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, TEACHERBUDDY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. IN NO EVENT SHALL TEACHERBUDDY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE PLATFORM.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">10. Modifications to This Agreement</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                We reserve the right to amend this Agreement at any time. Material changes will be communicated via email or through a conspicuous notice within the application no less than thirty (30) days prior to effectiveness. Continued use of the platform after such notice constitutes acceptance of the revised terms.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-4">11. Contact Information</h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                For inquiries regarding this Agreement, data subject requests, or complaints, please contact:
              </p>
              <p className="text-orange-600 dark:text-orange-400 font-medium mt-2">
                Email: graderelite@gmail.com
              </p>
            </section>
          </div>

          <div className="mt-12 text-center">
            <Link href="/">
              <Button className="bg-orange-500 hover:bg-orange-600 text-white" data-testid="button-back-home">
                Back to Home
              </Button>
            </Link>
          </div>
        </div>
      </main>

      <footer className="border-t bg-white dark:bg-slate-900 py-6">
        <div className="max-w-5xl mx-auto px-4 flex flex-col items-center gap-4">
          <img 
            src="/logo.png" 
            alt="TeacherBuddy" 
            className="h-12 object-contain opacity-80"
            data-testid="img-footer-logo"
          />
          <p className="text-sm text-slate-500 dark:text-slate-400 text-center">
            Built by teachers, for teachers.
          </p>
        </div>
      </footer>
    </div>
  );
}
